### PR TITLE
chore: update vendor data

### PR DESCRIPTION
**Pull request by erykpiast**
It was last updated in the first half of the year, which makes the `last X versions` queries quite outdated. For instance, the last Chrome version as for today is 131, but the tool returns  125.

### CODE REVIEW

**Comment by erykpiast** [comment]
Hey @g-plane, are you going to update subprojects yourself some time soon?

**Comment by g-plane** [comment]
What's "subprojects"?

**Comment by erykpiast** [comment]
I mean vendor projects. This is what this PR was supposed to do. I may miss the point of having this repos linked like this, but I've seen this approach in the commit history before, [like in here ](https://github.com/browserslist/browserslist-rs/commit/ddfebee1b27086c6cc763370a0a31e7c7e1bf296). I see you did this now with https://github.com/browserslist/browserslist-rs/commit/c0472dfc211739d540b7666a5f756b72ea9e3431, so all good! It means that v0.16.1 should include both my changes, correct?

**Comment by g-plane** [comment]
Sure.

**Pull request closed without merging**
